# Generated by Django 4.2 on 2024-04-03 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id_hab', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Id habitación')),
                ('id_tipo_hab', models.IntegerField(verbose_name='ID tipo habitación')),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo habitación')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('cantidad', models.CharField(max_length=50, verbose_name='Cantidad Habitaciones')),
                ('precio', models.CharField(max_length=50, verbose_name='Precio')),
                ('imagen', models.TextField(blank=True, null=True, verbose_name='Datos de la imagen en base64')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroUsuario',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Id usuario')),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombres del usuario')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos del usuario')),
                ('correo', models.EmailField(max_length=50, verbose_name='Correo del usuario')),
                ('telefono', models.CharField(default='', max_length=25, verbose_name='Teléfono del usuario')),
                ('contrasena', models.CharField(default='', max_length=25, verbose_name='Contraseña del usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ReporteReserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Id reserva')),
                ('dia_ingreso', models.DateField(auto_now_add=True)),
                ('hora_ingreso', models.TimeField(auto_now=True)),
                ('dia_salida', models.DateField()),
                ('hora_salida', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('id_tipo_hab', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID tipo habitación')),
                ('tipo_hab', models.CharField(max_length=25, verbose_name='Tipo habitación')),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_tipo_usuario', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre_tipo_usuario', models.CharField(max_length=20, verbose_name='Nombre tipo usuario')),
            ],
        ),
    ]
