# Generated by Django 5.0.3 on 2024-04-25 17:56

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosBancarios',
            fields=[
                ('id_banco', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Id Banco')),
                ('beneficiario', models.CharField(max_length=50, verbose_name='Beneficiario')),
                ('cuenta', models.CharField(max_length=50, verbose_name='Cuenta')),
                ('nro_cuenta', models.CharField(max_length=50, verbose_name='Número cuenta bancaria')),
                ('correo_banco', models.CharField(max_length=50, verbose_name='Correo Banco')),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id_hab', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Id habitación')),
                ('id_tipo_hab', models.IntegerField(verbose_name='ID tipo habitación')),
                ('titulo_hab', models.CharField(max_length=50, verbose_name='Titulo habitación')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('titulo_en', models.CharField(max_length=50, verbose_name='Titulo habitación en inglés')),
                ('descripcion_en', models.CharField(max_length=200, verbose_name='Descripción en inglés')),
                ('capacidad_max', models.IntegerField(verbose_name='Capacidad Máxima habitación')),
                ('precio', models.CharField(max_length=50, verbose_name='Precio')),
                ('estado', models.CharField(default='Disponible', max_length=50, verbose_name='Estado')),
                ('imagen', models.TextField(blank=True, null=True, verbose_name='Datos de la imagen en base64')),
            ],
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id_metodo_pago', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Id Metodo Pago')),
                ('tipo_metodo_pago', models.CharField(max_length=20, verbose_name='Metodo Pago')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroUsuario',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Id usuario')),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombres del usuario')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos del usuario')),
                ('correo', models.EmailField(max_length=50, verbose_name='Correo del usuario')),
                ('telefono', models.CharField(default='', max_length=25, verbose_name='Teléfono del usuario')),
                ('contrasena', models.CharField(default='', max_length=25, verbose_name='Contraseña del usuario')),
                ('rol', models.CharField(blank=True, default='Cliente', max_length=20, null=True, verbose_name='Rol del usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ReporteReserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Id reserva')),
                ('dia_ingreso', models.DateField(verbose_name='Dia Ingreso')),
                ('hora_ingreso', models.TimeField(blank=True, null=True)),
                ('dia_salida', models.DateField(verbose_name='Dia Salida')),
                ('hora_salida', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Id reserva')),
                ('id_user', models.CharField(max_length=20, verbose_name='Id Usuario')),
                ('order_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Id Orden PayPal')),
                ('fecha_llegada', models.DateField(verbose_name='Fecha Llegada')),
                ('fecha_salida', models.DateField(verbose_name='Fecha Salida')),
                ('cant_adultos', models.IntegerField(verbose_name='Cantidad Adultos')),
                ('cant_ninos', models.IntegerField(null=True, verbose_name='Cantidad Niños')),
                ('habitacion', models.CharField(max_length=50, verbose_name='Habitacion')),
                ('tipo_metodo_pago', models.CharField(max_length=20, verbose_name='Metodo Pago cliente')),
                ('total', models.IntegerField(verbose_name='Total Reserva')),
                ('pago_inicial', models.IntegerField(verbose_name='Pago Inicial Reserva')),
                ('pago_pendiente', models.IntegerField(verbose_name='Pago Pendiente')),
                ('estado_pago', models.CharField(default='Pendiente', max_length=20, verbose_name='Estado Pago')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('id_tipo_hab', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID tipo habitación')),
                ('tipo_hab', models.CharField(max_length=25, verbose_name='Tipo habitación')),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_tipo_usuario', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre_tipo_usuario', models.CharField(max_length=20, verbose_name='Nombre tipo usuario')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('cliente', 'Cliente'), ('admin', 'Administrador'), ('vendedor', 'Vendedor')], default='cliente', max_length=20)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appPacific.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(related_name='custom_user_set', through='appPacific.UserGroup', to='auth.group'),
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appPacific.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(related_name='custom_user_set', through='appPacific.UserPermission', to='auth.permission'),
        ),
    ]
