# Generated by Django 4.1 on 2024-01-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroUsuario',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Id usuario')),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombres del usuario')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos del usuario')),
                ('correo', models.EmailField(max_length=50, verbose_name='Correo de usuario')),
                ('nombre_usuario', models.CharField(max_length=25, verbose_name='Nombre de usuario')),
                ('direccion', models.CharField(max_length=60, verbose_name='Dirección de usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ReporteReserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Id reserva')),
                ('dia_ingreso', models.DateField(auto_now_add=True)),
                ('hora_ingreso', models.TimeField(auto_now=True)),
                ('dia_salida', models.DateField()),
                ('hora_salida', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_tipo_usuario', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre_tipo_usuario', models.CharField(max_length=20, verbose_name='Nombre tipo usuario')),
            ],
        ),
    ]
