# Generated by Django 4.2 on 2024-03-31 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPacific', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id_hab', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Id habitacion')),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo habitacion')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripcion')),
                ('cantidad_disp', models.CharField(max_length=50, verbose_name='Cantidad Habitaciones')),
                ('precio', models.CharField(max_length=50, verbose_name='Nombres del usuario')),
                ('imagen', models.ImageField(upload_to='habitacion_imagenes/', verbose_name='Imagen de la habitacion')),
            ],
        ),
        migrations.RemoveField(
            model_name='registrousuario',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='registrousuario',
            name='nombre_usuario',
        ),
        migrations.AddField(
            model_name='registrousuario',
            name='contrasena',
            field=models.CharField(default='', max_length=25, verbose_name='Contraseña del usuario'),
        ),
        migrations.AddField(
            model_name='registrousuario',
            name='telefono',
            field=models.CharField(default='', max_length=25, verbose_name='Teléfono del usuario'),
        ),
        migrations.AlterField(
            model_name='registrousuario',
            name='correo',
            field=models.EmailField(max_length=50, verbose_name='Correo del usuario'),
        ),
    ]
