# Generated by Django 5.0.3 on 2024-04-01 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPacific', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id_hab', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Id habitación')),
                ('id_tipo_hab', models.IntegerField(verbose_name='ID tipo habitación')),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo habitación')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('cantidad', models.CharField(max_length=50, verbose_name='Cantidad Habitaciones')),
                ('precio', models.CharField(max_length=50, verbose_name='Precio')),
                ('imagen', models.TextField(blank=True, null=True, verbose_name='Datos de la imagen en base64')),
            ],
        ),
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('id_tipo_hab', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID tipo habitación')),
                ('tipo_hab', models.CharField(max_length=25, verbose_name='Tipo habitación')),
            ],
        ),
    ]
