# Generated by Django 5.0.3 on 2024-04-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPacific', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipohabitacion',
            name='id_tipo_hab',
            field=models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID tipo habitación'),
        ),
    ]
