# Generated by Django 4.2 on 2024-04-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPacific', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrousuario',
            name='rol',
            field=models.CharField(blank=True, default='Cliente', max_length=20, null=True, verbose_name='Rol del usuario'),
        ),
    ]
